# Generated by Django 4.1 on 2022-08-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_reply_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Post',
            new_name='Database_Post',
        ),
        migrations.AddField(
            model_name='comments',
            name='User_Post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.publishblog'),
        ),
    ]
