# Generated by Django 4.1 on 2022-08-29 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_post_comments_database_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='User_Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publishblog'),
        ),
    ]
