# Generated by Django 4.1 on 2022-08-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comments_user_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Database_Post',
            new_name='Post',
        ),
    ]
